modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/aurilisdev/Extended-Tools" #optional
[[mods]] #mandatory
modId="extendedtools" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Extended Tools" #mandatory
displayURL="https://github.com/aurilisdev/Extended-Tools" #optional
logoFile="extendedtools.png" #optional
credits="Thanks to all contributors" #optional
authors="aurilisdev, pyro206" #optional
description='''
'''